function index_htmlload () {
  document.write('')
  document.write('	')
  document.write('		<div id="datachoice_sidebar" name="Datachoice_Panel" class="sidebar"> ')
  document.write('  <b>Choose data source<\/b>')
  document.write('  <hr>')
  document.write('		<font size=2px color=black>Epidemiological Data:<\/font>')
  document.write('		<select class="form-control" name="datachoice_sidebar_list" id="datachoice_sidebar_list">')
  document.write('			<option value="Start" selected="selected">Please Select<\/option>')
  document.write('			<option value="Population">Population<\/option>')
  document.write('			<option value="SIR">SIR\/CI<\/option>')
  document.write('			<option value="Causeeffect">Cause-effect info<\/option>')
  document.write('		<\/select>')
  document.write('		<br>')
  document.write('		<font size=2px color=black>Environmental Data:<\/font>')
  document.write('		<select class="form-control" name="datachoice_sidebar_list_env" id="datachoice_sidebar_list_env">')
  document.write('			<option value="Start" selected="selected">Please Select<\/option>')
  document.write('			<option value="Airquality">Air quality<\/option>')
  document.write('			<option value="Soildata">Soil data<\/option>')
  document.write('			<option value="Emitter">Emitter example Muenster<\/option>')
  document.write('			<option value="Accident">Accident data example<\/option>')
  document.write('		<\/select>')
  document.write('		<br>')
  document.write('		<font size=2px color=black>Explore Data:<\/font>')
  document.write('		<select class="form-control" name="datachoice_sidebar_list_linked" id="datachoice_sidebar_list_linked">')
  document.write('			<option value="Start" selected="selected">Please Select<\/option>')
  document.write('			<option value="Linkedinformation">Show linked information<\/option>')
  document.write('		<\/select>')
  document.write('		')
  document.write('		')
  document.write('		<!--	<button type="submit" class="btn btn-primary" onclick="visualization_example ()">Visualization_Example<\/button><br\/><br\/> -->')
  document.write('		<\/div>	')
  document.write('			')
  document.write('	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation" >')
  document.write('		  <div class="navbar-header pull-left">')
  document.write('			 ')
  document.write('			  <!--<div style="position:absolute;left:30%;top:20%;"><button type="button" onclick="Query()">Query<\/button><\/div>-->')
  document.write('			  <a class="navbar-brand" href="#" ><font color="white">C<\/font>ancer<font color="white">E<\/font>xplorer<\/a>')
  document.write('			')
  document.write('		<!--	<div class="collapse navbar-collapse"> -->')
  document.write('			  <ul class="nav navbar-nav">')
  document.write('				<li onclick="" ><a href="#"><font size="3px">Map<\/font><\/a><\/li>')
  document.write('				')
  document.write('				<li onclick="Sparql_panel_edit()"><a href="#"><font size="3px">SPARQL Query<\/font><\/a><\/li>')
  document.write('				<li onclick="Query()"><a href="#"><font size="3px">Explore cancer incidents<\/font><\/a><\/li>')
  document.write('				<li onclick="Explore_cause_effect();"><a href="#"><font size="3px">Explore cause-effect relations<\/font><\/a><\/li>')
  document.write('				<!---->')
  document.write('				<li onclick=""><a id="GetLocation" href="#"><font size="3px">Get my location<\/font><\/a><\/li>')
  document.write('				')
  document.write('				')
  document.write('				<!--Add information:-->')
  document.write('				<li onclick="Links.show();"><a href="#"><font size="3px">Further links<\/font><\/a><\/li>')
  document.write('				<li onclick="introjs();"><a href="#" title="Explains the functionalities of the application"><span STYLE="color:#00AFF0; font-size: 14pt" class="glyphicon glyphicon-info-sign"><\/span><\/a><\/li>')
  document.write('				')
  document.write('				')
  document.write('				  ')
  document.write('				')
  document.write('			  <\/ul>')
  document.write('		<!--	<\/div><!--\/.nav-collapse -->')
  document.write('		  <\/div>')
  document.write('		<\/div>')
  document.write('')
  document.write('	<!-- Main div structure on page style="position:absolute;left:25px; top:51px; width: 40%; height: 80%;"-->')
  document.write('		')
  document.write('<!-- Div for the backgroundinformation -->')
  document.write("	<div id='popup_div'><\/div>")
  document.write('	')
  document.write('		<div id="map" style="position:absolute;left:25px; top:51px; width: 97%; height: 80%;" >')
  document.write('		')
  document.write('		')
  document.write('	 ')
  document.write('	  ')
  document.write('	 ')
  document.write('	  ')
  document.write('	 ')
  document.write('	  ')
  document.write('	 <!-- sir sidebar -->')
  document.write('')

  document.write('	 <div id="sir_sidebar" name="sir_sidebar" class="sidebar"> ')
  document.write('		<br> <b><font size=4px>Create a certain Example Standardized Incidence Ratio (SIR) visualization:  <\/b><\/font>')
  document.write('		<br>')
  document.write('		<div style="padding-top:15px">')
  document.write('			<b><font size=3px>Choose a cancer type:<\/b><\/font>')
  document.write('		<\/div>')
  document.write('		<div style="border: thin solid #000000; border-bottom-width: 0px;">')
  document.write('		<\/div>')
  document.write('		<div style="padding-top:10px">')
  document.write('			<input type="radio" id="sirbladdercancer" class="obsType" name="obsType" value="C67" checked="checked">&nbsp;Bladder cancer &nbsp;')
  document.write('			<input type="radio" id="sirlungcancer" class="obsType" name="obsType" value="C34">&nbsp;Lung cancer &nbsp;')
  document.write('			<input type="radio" id="sirleukemiacancer" class="obsType" name="obsType" value="C91-C95">&nbsp;Leukemia &nbsp;&nbsp;&nbsp;<br>')
  document.write('			<input type="radio" id="sirnasalcancer" class="obsType" name="obsType" value="C00-C14">&nbsp;Nasal cavity and paranasal sinus &nbsp;')
  document.write('			')
  document.write('		<\/div>')
  document.write('		<br>')
  document.write('		')
  document.write('		<div style="padding-top:15px">')
  document.write('			<b><font size=3px>Choose a year:<\/b><\/font>')
  document.write('		<\/div>')
  document.write('		<div style="border: thin solid #000000; border-bottom-width: 0px;">')
  document.write('		<\/div>')
  document.write('		<div style="padding-top:10px">')
  document.write('			<input type="radio" id="sir2006" name="obsType1" value="2006">&nbsp;2006 &nbsp;')
  document.write('			<input type="radio" id="sir2007" name="obsType1" value="2007">&nbsp;2007 &nbsp;')
  document.write('			<input type="radio" id="sir2008" name="obsType1" value="2008">&nbsp;2008 &nbsp;')
  document.write('			<input type="radio" id="sir2009" name="obsType1" value="2009">&nbsp;2009 &nbsp;')
  document.write('			<input type="radio" id="sir2010" name="obsType1" value="2010">&nbsp;2010 &nbsp;')
  document.write('			<input type="radio" id="sir2011" name="obsType1" value="2011">&nbsp;2011 &nbsp;')
  document.write('		<\/div>')
  document.write('			')
  document.write('		')
  document.write('		')
  document.write('		<hr>')
  document.write('		')
  document.write('		<div style="padding-top:15px">')
  document.write('			<b><font size=3px>Choose a gender:<\/b><\/font>')
  document.write('		<\/div>')
  document.write('		<div style="border: thin solid #000000; border-bottom-width: 0px;">')
  document.write('		<\/div>')
  document.write('		<div style="padding-top:10px">')
  document.write('		    <input type="radio" id="sirfemale" name="obsType2" value="w">&nbsp;female')
  document.write('			<input type="radio" id="sirmale" name="obsType2" value="m">&nbsp;male &nbsp;&nbsp;')
  document.write('		')
  document.write('		<\/div>')
  document.write('			')
  document.write('		<br>')
  document.write('		<hr>')
  document.write('		<input type=checkbox id="SIR_check" name="SIR" value="" checked="false" class="chechbox_map1" onClick="validate_sir(map,\'map\',\'SIR\');">Show\/Hide SIR Data<\/input>')
  document.write('		<div  id="SIR_check_map2_div2">')
  document.write('		<input type=checkbox id="SIR_check_map2" name="SIR2" value="" checked="false" class="chechbox_map2" onClick="validate_sir(map2,\'map2\',\'SIR\');">Show\/Hide SIR Data on map2<\/input>	')
  document.write('		<\/div>')
  document.write('		<hr>')
  document.write('		<input type=checkbox id="CIlower_check" name="CIlower" value="" checked="false" class="chechbox_map1" onClick="validate_sir(map,\'map\',\'CI_lower_level\');">Show\/Hide CI95 Lower Level<\/input>	')
  document.write('		<div   id="CIlower_check_map2_div">')
  document.write('		<input type=checkbox  id="CIlower_check_map2" name="CIlower" value="" checked="false" class="chechbox_map2" onClick="validate_sir(map2,\'map2\',\'CI_lower_level\');">Show\/Hide CI95 Lower Level on map2<\/input>	')
  document.write('		<\/div>')
  document.write('		<hr>')
  document.write('		<input type=checkbox id="CIupper_check" name="CIupper" value="" checked="false" class="chechbox_map1" onClick="validate_sir(map,\'map\',\'CI_upper_level\');">Show\/Hide CI95 Upper Level<\/input>	')
  document.write('		<div   id="CIupper_check_map2_div">')
  document.write('		<input type=checkbox  id="CIupper_check_map2" name="CIupper" value="" checked="false" class="chechbox_map2" onClick="validate_sir(map2,\'map2\',\'CI_upper_level\');">Show\/Hide CI95 Upper Level on map2<\/input>	')
  document.write('		<\/div>')
  document.write('		<hr>')
  document.write('		')
  document.write('		')
  document.write('		')
  document.write('		')
  document.write('		')
  document.write('			<button id="ClearSelection" type="button" onclick="sir_clear()" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Clear Selection<\/button>')
  document.write('	<!--		<button id="Visualize1" type="button" onclick="ini_sir()" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Visualize Example SIR<\/button>')
  document.write('			<button id="Visualize2" type="button" onclick="ini_cilower()" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Visualize Example CI95 Lower Level<\/button> ')
  document.write('			<button id="Visualize3" type="button" onclick="ini_ciupper()" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Visualize Example CI95 Upper Level<\/button>	-->	')
  document.write('		<\/div>')
  document.write('')
  document.write('')
  document.write('		<div id="SPARQLPanel" name="SPARQLPanel" class="sidebar">')
  document.write('			<!-- empty html div-element ... placeholder for results (text\/canvas\/map etc)-->')
  document.write('			<div id="resultdiv"><\/div>')
  document.write('			<br\/>')
  document.write('		<\/div>')
  document.write('	  ')
  document.write('		<div id="SPARQLPanel_edit" name="SPARQLPanel_edit" class="sidebar">')
  document.write('			<textarea id="sparqlQuery" rows="5" cols="40" class="field span12">Select ?a ?b ?c WHERE {?a ?b ?c} Limit 10<\/textarea><br\/>')
  document.write('			<button type="submit" class="btn btn-primary" onclick="SPedit()">Submit Query<\/button><br\/><br\/>')
  document.write('')
  document.write('			<!-- empty html div-element ... placeholder for results (text\/canvas\/map etc)-->')
  document.write('			<div id="resultdiv_edit"><\/div>')
  document.write('				<br\/>	')
  document.write('		<\/div>')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	<div id="overlaydata_sidebar" name="OverlayData_Panel"  class="sidebar"> ')
  document.write('	<b>Population<\/b>')
  document.write('	<hr>')
  document.write('		<font style="width: 20%" size=2px color=black>Choose a gender:<\/font>')
  document.write('		<input type="radio" id="popfemale" name="obsType3" value="female">&nbsp;female')
  document.write('		<input type="radio" id="popmale" name="obsType3" value="male">&nbsp;male &nbsp;&nbsp;')
  document.write('		<\/br>')
  document.write('')
  document.write('				<font style="width: 20%" size=2px color=black>Choose an age class:<\/font>')
  document.write('			<select  class="form-control" name="list_popageclass" id="list_popageclass">')
  document.write('			<option selected value="">Age-Class<\/option>')
  document.write('			<option value="1">0-4<\/option>')
  document.write('			<option value="2">5-9<\/option>')
  document.write('			<option value="3">10-14<\/option>')
  document.write('			<option value="4">15-19<\/option>')
  document.write('			<option value="5">20-24<\/option>')
  document.write('			<option value="6">25-29<\/option>')
  document.write('			<option value="7">30-34<\/option>')
  document.write('			<option value="8">35-39<\/option>')
  document.write('			<option value="9">40-44<\/option>')
  document.write('			<option value="10">45-49<\/option>')
  document.write('			<option value="11">50-54<\/option>')
  document.write('			<option value="12">55-59<\/option>')
  document.write('			<option value="13">60-64<\/option>')
  document.write('			<option value="14">65-69<\/option>')
  document.write('			<option value="15">70-74<\/option>')
  document.write('			<option value="16">75-79<\/option>')
  document.write('			<option value="17">80-84<\/option>')
  document.write('			<option value="18">85+<\/option>')
  document.write('		<\/select>')
  document.write('					')
  document.write('			<font style="width: 20%" size=2px color=black>Choose a year:<\/font>')
  document.write('		<select class="form-control" name="list_popyear" id="list_popyear">')
  document.write('			<option selected value="">Year<\/option>')
  document.write('			<option value="2004">2004<\/option>')
  document.write('			<option value="2005">2005<\/option>')
  document.write('			<option value="2006">2006<\/option>')
  document.write('			<option value="2007">2007<\/option>')
  document.write('			<option value="2008">2008<\/option>')
  document.write('			<option value="2009">2009<\/option>')
  document.write('			<option value="2010">2010<\/option>')
  document.write('			<option value="2011">2011<\/option>')
  document.write('		<\/select>')
  document.write('		<input type=checkbox id="Population_check" name="Population" value="" checked="false" onClick="validate_pop(map,\'map\');">Show\/Hide Population Data<\/input>	')
  document.write('		<hr>')
  document.write('		<div id="population_map2" >')
  document.write('		<input type=checkbox id="Population_check_map2" name="Population" value="" checked="false" onClick="validate_pop(map2,\'map2\');">Show\/Hide Population Data on map2<\/input>	')
  document.write('		<\/div>')
  document.write('	<\/div>')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	<div id="linkedinformation_sidebar" name="Linkedinformation_Panel" class="sidebar"> ')
  document.write('		')
  document.write('			<font style="width: 20%" size=2px color=black>Choose an object you want to know more about<\/font>')
  document.write('			<select  class="form-control" onchange="seeAlso_info();" name="list_linkedinformation" id="rdfsseeAlso_list">')
  document.write('			<option selected value="Start">Please Select<\/option>')
  document.write('		    <\/select>')
  document.write('				<br\/>')
  document.write('				')
  document.write('				<font style="width: 20%" size=2px color=black>Abstract:<\/font>')
  document.write('				<br\/>')
  document.write('				<div id="side" style="auto">')
  document.write('						<!--<select id="dbpedia_abstract"name="sometext" size="5" onchange=""  style="width:300px; text-align:left;"  > -->')
  document.write('						<textarea id="dbpedia_abstract" style="width: 100%;height: 10%;" ><\/textarea>')
  document.write('						<!--<option label="Abstract"><\/option> ')
  document.write('						<\/select> -->')
  document.write('						<\/div>')
  document.write('				')
  document.write('				<br\/>')
  document.write('				<font style="width: 20%" size=2px color=black>Further external links:<\/font>')
  document.write('				<br\/>')
  document.write('				<div id="side" style="auto">')
  document.write('						<select id="dbpedia_links"name="sometext" size="5" onchange="link_click(\'dbpedia_links\');"  style="width:100%; text-align:left;"  >')
  document.write('						<\/select>')
  document.write('						<\/div>')
  document.write('				')
  document.write('				')
  document.write('				')
  document.write('				<br\/>')
  document.write('				<font style="width: 20%" size=2px color=black>Click for more information:<\/font>')
  document.write('				<br\/>')
  document.write('				<div id="side" style="float:left;margin-right:20px;">')
  document.write('						<select id="seeAlso_source"name="sometext" size="5" onchange="seeAlso_source_click();"  style="width:100%; text-align:center;"  >')
  document.write('						<option label="SeeAlso"><\/option> ')
  document.write('						<\/select>')
  document.write('						<\/div>')
  document.write('			')
  document.write('	<\/div>')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('')
  document.write('	<!-- Definition of link sidebar-->')
  document.write('	<!-- Currently not used-->')
  document.write('')
  document.write('')
  document.write('	 <div id="sidebarLinks" name="sidebarLinks" class="sidebar"> ')
  document.write('')
  document.write('	<h>Here should be some further information.<\/h>')
  document.write('	<br>')
  document.write('')
  document.write('	<\/div>')
  document.write('	')
  document.write('	')
  document.write('	<div id="sidebarAskData" name="sidebarAskData" class="sidebar"> ')
  document.write('')
  document.write('	<h>Here should be some further information.<\/h>')
  document.write('	<br>')
  document.write('')
  document.write('	<\/div>')
  document.write('	<div id="causeeffect_sidebar" name="sidebarcauseeffect" class="sidebar"> ')
  document.write('	<\/div>')

  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('')
  document.write('')
  document.write('')
  document.write('')
  document.write('		<div id="Cause_Effect_Panel" name="Cause_Effect_Panel" class="sidebar"> ')
  document.write('')
  document.write('			<br> <b><font size=4px>Get more information about cancer causes:  <\/b><\/font>')
  document.write('			<div style="border: thin solid #000000; border-bottom-width: 0px;">')
  document.write('				<\/div>')

  document.write('				<button type="button" onclick="close_background_modus()" class="btnStyle span3" value="Get Background Information" data-color="#00aff0" data-hover="#0cbbfc" id="Background">Get Background Information<\/button>')

  document.write('				<br>')
  document.write('				<div style="padding-top:15px">')
  document.write('					<b><font size=4px>Further information examples:  <\/b><\/font>')
  document.write('				<\/div>')
  document.write('				<div style="border: thin solid #000000; border-bottom-width: 0px;">')
  document.write('				<\/div>')
  document.write('				<br>')
  document.write('				<b><font size=2px>Show examples for biggest emitter of air transported substances in M&uuml;nster<\/b><\/font>')
  document.write('				<br>')
  document.write('				<button type="button" onclick="ini_emitter()" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc" id="Emitter">Example emitter M&uuml;nster <\/button>')
  document.write('				<b><font size=2px>Shows a example set for industrial accidents<\/b><\/font>')
  document.write('				<button type="button" onclick="ini_accident()" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc" id="Accident">Example industrial accident data <\/button>')
  // document.write("				<button type=\"button\" onclick=\"dvf2(WLBoundaries,'properties','GKZ')\" class=\"btnStyle span3\" data-color=\"#00aff0\" data-hover=\"#0cbbfc\" id=\"DVF-Test\">DVF <\/button>")
  document.write('<!--')
  document.write('		<button id="ExploreSoildata" type="button" onclick="ini_soildata()" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Explore Soil Data<\/button>')
  document.write('<!--')
  document.write('		<font size=2px color=white>Choose a municipality for soildata exploration<\/font>')
  document.write('		<select class="form-control" name="list_soildata" id="list_soildata" onchange="visualize_soildatamarker2 ();">')
  document.write('		<option value="start">Please Select<\/option>')
  document.write('		<\/select>')
  document.write('-->')
  document.write('		<br>')
  document.write('		<\/div>')
  document.write('')
  document.write('')
  document.write('')
  document.write('		<div id="Emitter_detail"> ')
  document.write('')
  document.write('			<h3>Emitter details:<\/h3>')
  document.write('			<form>')
  document.write('			  <fieldset>')
  document.write('				<legend>Address<\/legend>')
  document.write('				<table>')
  document.write('				  <tr>')
  document.write('					<td><b>Name:<\/b><\/td>')
  document.write('					<td><div id="name_emit"> <\/div><\/td>')
  document.write('					<td><b>Zip & City:<\/b><\/td>')
  document.write('					<td><div id="zip_emit"> <\/div><\/td>')
  document.write('				  <\/tr><tr>')
  document.write('					<td><b>Street:<\/b><\/td>')
  document.write('					<td><div id="street_emit"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <\/br>')
  document.write('				  <tr>')
  document.write('					<td><b>Emission process:<\/b><\/td>')
  document.write('					<td><div id="emissionprocess"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				<\/table>')
  document.write('			  <\/fieldset>')
  document.write('			  <br>')
  document.write('			  <fieldset>')
  document.write('				<legend>Emitted substances<\/legend>')
  document.write("				<b>Emissions from operator of the facility's emissions declaration 2008.<\/b><br>")
  document.write('				<b>Measurements in kg\/a, Dioxine\/Furane as I-TE in mg\/a. <\/b><br>')
  document.write('			  <br>')
  document.write('			  <br>  ')
  document.write('			  <table align="center">')
  document.write('			      <tr bgcolor="#58ACFA">    ')
  document.write('					<td><b>Substances:<\/b><\/td><td>        <\/td>')
  document.write('					<td><b>Values:<\/b><\/div><\/td>')
  document.write('				  <\/tr><tr>')
  document.write('					<td><b>N2O<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="N2O"> <\/div><\/td>')
  document.write('				  <\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>CO2<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="CO2"> <\/div><\/td>')
  document.write('				  <\/tr><tr>')
  document.write('					<td><b>CH4<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="CH4"> <\/div><\/td>')
  document.write('				  <\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>NH3<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="NH3"> <\/div><\/td>')
  document.write('				  <\/tr><tr>')
  document.write('					<td><b>HCL<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="HCL"> <\/div><\/td>					')
  document.write('				  <\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>HF<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="HF"> <\/div><\/td>')
  document.write('					<\/tr><tr>')
  document.write('					<td><b>CO<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="CO"> <\/div><\/td>')
  document.write('					<\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>NMVOC<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="NMVOC"> <\/div><\/td>')
  document.write('					<\/tr><tr>')
  document.write('					<td><b>SO2<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="SO2"> <\/div><\/td>')
  document.write('					<\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>NO2<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="NO2"> <\/div><\/td>')
  document.write('					<\/tr><tr>')
  document.write('					<td><b>As<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="As"> <\/div><\/td>')
  document.write('					<\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>Pb<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="Pb"> <\/div><\/td>')
  document.write('					<\/tr><tr>')
  document.write('					<td><b>Cr<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="Cr"> <\/div><\/td>')
  document.write('					<\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>Cu<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="Cu"> <\/div><\/td>')
  document.write('					<\/tr><tr>')
  document.write('					<td><b>Cd<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="Cd"> <\/div><\/td>')
  document.write('					<\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>Ni<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="Ni"> <\/div><\/td>')
  document.write('					<\/tr><tr>')
  document.write('					<td><b>V<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="V"> <\/div><\/td>')
  document.write('					<\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>Zn<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="Zn"> <\/div><\/td>')
  document.write('					<\/tr><tr>')
  document.write('					<td><b>DUF<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="DUF"> <\/div><\/td>')
  document.write('					<\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>BAP<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="BAP"> <\/div><\/td>')
  document.write('					<\/tr><tr>')
  document.write('					<td><b>BENZ<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="BENZ"> <\/div><\/td>')
  document.write('					<\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>PAK<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="PAK"> <\/div><\/td>')
  document.write('					<\/tr><tr>')
  document.write('					<td><b>PM10<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="PM10"> <\/div><\/td>')
  document.write('					<\/tr><tr bgcolor="#D8D8D8">')
  document.write('					<td><b>Staub<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="Staub"> <\/div><\/td>')
  document.write('					<\/tr><tr>')
  document.write('					<td><b>RUSS<\/b><\/td><td>        <\/td>')
  document.write('					<td><div id="RUSS"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				<\/table>')
  document.write('				<br>')
  document.write('				<b>Source:<\/b><br>')
  document.write('				<b>Landesamt f&uuml;r Natur, Umwelt und Verbraucherschutz<br>')
  document.write('				   © Land NRW, Recklinghausen, http:\/\/www.lanuv.nrw.de<\/b><br>')
  document.write('				')
  document.write('			  <\/fieldset>')
  document.write('			<\/form>')
  document.write('')
  document.write('')
  document.write('		<\/div>')
  document.write('')
  document.write('')
  document.write('	 ')
  document.write('	<\/div>')
  document.write('	')
  document.write('	')
  document.write('	<div id="Accident_detail"> ')
  document.write('')
  document.write('			<h3>Industrial accident details:<\/h3>')
  document.write('			<form>')
  document.write('			  <fieldset>')
  document.write('				<legend>Address<\/legend>')
  document.write('				<table>')
  document.write('				  <tr>')
  document.write('					<td><b>Name:<\/b><\/td>')
  document.write('					<td><div id="name_acc"> <\/div><\/td>')
  document.write('				  <\/tr><tr>')
  document.write('					<td><b>Street:<\/b><\/td>')
  document.write('					<td><div id="street_acc"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <tr>')
  document.write('					<td><b>Zipcode:<\/b><\/td>')
  document.write('					<td><div id="zip_acc"> <\/div><\/td>')
  document.write('					<td><b>Municipality:<\/b><\/td>')
  document.write('					<td><div id="municipality"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <\/table>')
  document.write('				  <\/br>')
  document.write('				  <hr>')
  document.write('				  <legend>Incident details<\/legend>')
  document.write('				  <table>')
  document.write('				  <tr>')
  document.write('					<td><b>Type:<\/b><\/td>')
  document.write('					<td><div id="type"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <tr bgcolor="#D8D8D8">')
  document.write('					<td><b>Faulty part:<\/b><\/td>')
  document.write('					<td><div id="faultypart"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <tr>')
  document.write('					<td><b>Operation process:<\/b><\/td>')
  document.write('					<td><div id="operationprocess"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <tr bgcolor="#D8D8D8">')
  document.write('					<td><b>Cause:<\/b><\/td>')
  document.write('					<td><div id="cause"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <tr>')
  document.write('					<td><b>Cause status:<\/b><\/td>')
  document.write('					<td><div id="causestatus"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <tr bgcolor="#D8D8D8">')
  document.write('					<td><b>Environmental pollution status:<\/b><\/td>')
  document.write('					<td><div id="eps"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <tr>')
  document.write('					<td><b>Status of diverse disturbences:<\/b><\/td>')
  document.write('					<td><div id="sdd"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <tr bgcolor="#D8D8D8">')
  document.write('					<td><b>Year:<\/b><\/td>')
  document.write('					<td><div id="year"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <!--**')
  document.write('				   <tr>')
  document.write('					<td><b>Status of diverse disturbences:<\/b><\/td>')
  document.write('					<td><div id="accident_substance"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				   <tr bgcolor="#D8D8D8">')
  document.write('					<td><b>Status of diverse disturbences:<\/b><\/td>')
  document.write('					<td><div id="value_kg"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <tr>')
  document.write('					<td><b>Status of diverse disturbences:<\/b><\/td>')
  document.write('					<td><div id="value_text"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  <tr bgcolor="#D8D8D8">')
  document.write('					<td><b>Status of diverse disturbences:<\/b><\/td>')
  document.write('					<td><div id="value_description"> <\/div><\/td>')
  document.write('				  <\/tr>')
  document.write('				  -->')
  document.write('				<\/table>')
  document.write('			  <\/fieldset>')
  document.write('				<br>')
  document.write('				<button id="Accidentdetail" type="button" onclick="accident_detail_func();" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Get involved substance information<\/button>')
  document.write('				<b>Source:<\/b><br>')
  document.write('				<b>"Zentralen Melde- und Auswertestelle für Störfälle und Störungen in verfahrenstechnischen Anlagen" (ZEMA)<br>')
  document.write('				   infosys\/ZEMA, http:\/\/www.infosis.uba.de\/index.php\/de\/zema\/index.html<\/b><br>')
  document.write('				')
  document.write('			  <\/fieldset>')
  document.write('			<\/form>')
  document.write('		<\/div>')
  document.write('	<\/div>')
  document.write('')
  document.write('	')
  document.write('	')
  document.write('	 <div class="clear"><\/div>')
  document.write('	')
  document.write('	<div id="map2" style="float:left; margin-left:45%; top:51px; width: 0%; height: 0%;">')
  document.write('	<\/div>')
  document.write('	')
  document.write('	<div id="legend" style="position:absolute;left:655px; top:60px;" ><\/div>')
  document.write('	')
  document.write('	<div id="control" style=" float:right; margin-top:60px; margin-right:25px;  width: 10%; height: 0%;" hidden="true" background="white">')
  document.write('		 <font size=2px color="white"><b>Air Quality Data:<\/b><\/font>')
  document.write('		<button id="ExploreAirQuality" type="button" onclick="explorer_sidebar()" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Air Quality Data<\/button>')
  document.write('		<hr>')
  document.write('		<font size=2px color="white"><b> Soil Data: <\/b><\/font><br>')
  document.write('		<font size=2px color="white">Choose a municipality for soildata exploration<\/font>')
  document.write('		<select class="form-control" name="list_soildata2" id="list_soildata2" onchange="visualize_soildatamarker2();">')
  document.write('			<option value="start">Please Select<\/option>')
  document.write('		<\/select>')
  document.write('		')
  document.write('		<button id="Soildatadeleter" type="button" onclick="delete_soildata()" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Delete Soil Data<\/button>')
  document.write('		')
  document.write('		<button id="Soildatadeleter" type="button" onclick="delete_soildata();OverlayData_Panel.toggle();" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Get Age Distribution Info<\/button>')
  document.write('			')

  document.write('			<button  id="LeaveExplorer" type="button"   onclick="explorer_exit();" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Leave Explorer View<\/button>')

  document.write('	<\/div>')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	<div id="aqd_results_sidebar" name="AQDResultsPanel" class="sidebar"> ')
  document.write('		<div id="resultdiv_map2"><\/div>')
  document.write('	<\/div>')
  document.write('	')
  document.write('	<div id="explorer_sidebar"> ')
  document.write('		')
  document.write('	<div style="padding-top:15px">')
  document.write('		<b><font size=3px color=black>Choose an air emission value to explore:<\/b><\/font>')
  document.write('	<\/div>')
  document.write('	<div style="border: thin solid #000000; border-bottom-width: 0px;">')
  document.write('	<\/div>')
  document.write('		')
  document.write('		<font size=2px color=black>First, choose an emission branch<\/font>')
  document.write('		<select class="form-control" name="list_branch" id="list_branch">')
  document.write('			<option value="start">Please Select<\/option>')
  document.write('			<option value="Industry">Industry<\/option>')
  document.write('			<option value="Traffic">Traffic<\/option>')
  document.write('			<option value="SmallCombustionPlant">Small Combustion Plant<\/option>')
  document.write('			<option value="Agriculture">Agriculture<\/option>')
  document.write('			<option value="Total">All emission branches<\/option>')
  document.write('		<\/select>')
  document.write('		<br>')
  document.write('		<font size=2px color=black>Choose an emitted substance<\/font>')
  document.write('		<select class="form-control" name="list_substance" id="list_substance">')
  document.write('			<option value="start">Please Select<\/option>')
  document.write('			<option value="N2O">N2O<\/option>')
  document.write('			<option value="CO2">CO2<\/option>')
  document.write('			<option value="CH4">CH4<\/option>')
  document.write('			<option value="NH3">NH3<\/option>')
  document.write('			<option value="HCL">HCL<\/option>')
  document.write('			<option value="HF">HF<\/option>')
  document.write('			<option value="CO">CO<\/option>')
  document.write('			<option value="NMVOC">NMVOC<\/option>')
  document.write('			<option value="SO2">SO2<\/option>')
  document.write('			<option value="NO2">NO2<\/option>')
  document.write('			<option value="As">As<\/option>')
  document.write('			<option value="Pb">Pb<\/option>')
  document.write('			<option value="Cr">Cr<\/option>')
  document.write('			<option value="Cu">Cu<\/option>')
  document.write('			<option value="Cd">Cd<\/option>')
  document.write('			<option value="Ni">Ni<\/option>')
  document.write('			<option value="V">V<\/option>')
  document.write('			<option value="Zn">Zn<\/option>')
  document.write('			<option value="DUF">DUF<\/option>')
  document.write('			<option value="BAP">BAP<\/option>')
  document.write('			<option value="BENZ">BENZ<\/option>')
  document.write('			<option value="PAK">PAK<\/option>')
  document.write('			<option value="PM10">PM10<\/option>')
  document.write('			<option value="Staub">Staub<\/option>')
  document.write('			<option value="RUSS">RUSS<\/option>')
  document.write('		<\/select>')
  document.write('	<br>')
  // document.write("	<button type=\"button\" onclick=\"explorer_airquality()\" class=\"btnStyle span3\">Visualize<\/button>")
  document.write('	<input type=checkbox id="AQD_check" name="AQD_check" value="" checked="false" class="chechbox_map1" onClick="validate_aqd(\'map\');">Show\/Hide air quality data<\/input>')
  document.write('		<div id="AQD_check_map2_div2">')
  document.write('		<input type=checkbox id="AQD_check_map2" name="AQD_check" value="" checked="false" class="chechbox_map2" onClick="validate_aqd(\'map2\');">Show\/Hide air quality data on map2<\/input>	')
  document.write('	<\/div>')
  document.write('	<hr>')
  document.write('	<font color=black size=1px><b>Source: Landesamt f&uuml;r Natur, Umwelt und Verbraucherschutz<br>')
  document.write('				   © Land NRW, Recklinghausen, http:\/\/www.lanuv.nrw.de<\/b><br> ')
  document.write("				   <b>Emissions from operator of the facility's emissions declaration 2008.<\/b><br>")
  document.write('				   <b>Measurements in kg\/a, Dioxine\/Furane as I-TE in mg\/a. <\/b><br>   ')
  document.write('				   <\/font>')
  document.write('	<br\/>')

  document.write('	<\/div>')
  document.write('')
  document.write('')
  document.write('<div id="SoildataPanel_entry" name="SoildataPanel_entry" class="sidebar"class="sidebar">')
  document.write('	<font size=2px color="white">Choose a municipality for soildata exploration<\/font>')
  document.write('		<select class="form-control" name="list_soildata" id="list_soildata" onchange="visualize_soildatamarker2();">')
  document.write('			<option value="start">Please Select<\/option>')
  document.write('		<\/select>')
  document.write('		')
  document.write('		<button id="Soildatadeleter" type="button" onclick="delete_soildata()" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Delete Soil Data<\/button>')
  document.write('		')
  document.write('			')
  document.write('	<\/div>')
  document.write('')
  document.write('')
  document.write('')
  document.write('')
  document.write('')
  document.write('	')
  document.write('	')
  document.write('')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	<div id="SoildataPanel" name="SoildataPanel" class="sidebar">')
  document.write('	<\/div>')

  document.write('	<div id="Emitter_municipalityPanel" name="Emitter_municipalityPanel" class="sidebar">')
  document.write('<font size=2px color="white"><b> Emitter Data: <\/b><\/font><br>')
  document.write('		<font size=2px color="white">Choose a municipality for emitter exploration<\/font>')
  document.write('		<select class="form-control" name="list_emitterdata2" id="list_emitterdata2" onchange="visualize_emitterdatamarker2();">')
  document.write('			<option value="start">Please Select<\/option>')
  document.write('		<\/select>')
  document.write('		')
  document.write('		<button id="Emitterdatadeleter" type="button" onclick="clear_emitter_locations()" class="btnStyle span3" data-color="#00aff0" data-hover="#0cbbfc">Delete Emitter Data<\/button>')
  document.write('		')

  document.write('	<\/div>')

  document.write('	')
  document.write('	')
  document.write('	<div id="modal" style="border:3px solid black; background-color:#9999ff; padding:25px; font-size:150%; text-align:center; display:none;">')
  document.write('	<select class="form-control" name="list_municipalities4iarc" id="list_municipalities4iarc" onchange="visualize_emitter();">')
  document.write('			<option value="start">Please Select<\/option>')
  document.write('		<\/select>')
  document.write('	<input type="button" value="Close" onClick="Popup.hide(\'modal\')">')
  document.write('	<\/div>')
  document.write('	')
  document.write('	')
  document.write('		')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('	')
  document.write('')
  document.write('')
  document.write('	<\/div>')
  document.write('	<\/div>')
  document.write('')
  document.write('	<!-- Test Button -->')
  document.write('	<!--		<div style="padding-left: 10px;padding-right: 10px; position:absolute; bottom:-10px; width:100%;">')
  document.write('					<input type="button" id="Btn1" value="Sparql ME" onclick="jsonmerge();" class="btnStyle span3" \/> -->')
  document.write('				   ')
  document.write('		<\/div>		')
  document.write('')
  document.write('')
  document.write('		<div id="Links"> <a target="_blank" href="http://www.friedrichmueller-gi.de:8080/openrdf-workbench/repositories/NONE/repositories">Download RDF data sets<\/a> <\/br> Link with data and Ontolgy description is coming soon...<\/div>')
}
